### ISSUE TITLE
Automate AWS Lambda Deployments

### ISSUE THREAD

**Issue by vogt4nick** [datascience-bot/datascience-bot#30]
Let's deploy on tags.

Helpful to lookup [an example](https://github.com/vogt4nick/datascience-bot/blob/master/.travis.yml) from before:

```
deploy:
  - provider: lambda
    region: us-east-1
    role: arn:aws:iam::491984534845:role/datascience-bot-travis-ci
    runtime: python3.7
    function_name: datascience-bot
    module_name: lambda_function
    handler_name: lambda_handler
    timeout: 120
    zip: datascience-bot.zip
    on:
      branch: master
```
